GO

IF object_id('spUpdateDoctor') IS NULL
    EXEC ('create procedure dbo.spUpdateDoctor as select 1')
GO
ALTER PROCEDURE spUpdateDoctor
@ID INT, @FIRSTNAME VARCHAR(30), @LASTNAME VARCHAR(30), @PHONENUM BIGINT, @CABNUM TINYINT, @SPECIALITY VARCHAR(30), @ID_ROLE INT
AS
BEGIN
UPDATE DOCTORS
SET FIRSTNAME = @FIRSTNAME,
    LASTNAME = @LASTNAME,
	PHONENUM = @PHONENUM,
	CABNUM = @CABNUM,
	SPECIALITY = @SPECIALITY,
	ID_ROLE = @ID_ROLE
WHERE ID_DOCTOR = @ID;
END;

GO

IF object_id('spUpdateUser') IS NULL
    EXEC ('create procedure dbo.spUpdateUser as select 1')
GO
ALTER PROCEDURE spUpdateUser
@ID INT, @FIRSTNAME VARCHAR(30), @LASTNAME VARCHAR(30), @PHONENUM BIGINT, @EMAIL VARCHAR(320), @ID_ROLE INT
AS
BEGIN
UPDATE USERS
SET FIRSTNAME = @FIRSTNAME,
    LASTNAME = @LASTNAME,
	PHONENUM = @PHONENUM,
	EMAIL = @EMAIL,
	ID_ROLE = @ID_ROLE
WHERE ID_USER = @ID;
END;