USE LV_310_DENTISTRY;

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = 'ADMINS')
BEGIN
	CREATE TABLE ADMINS(
	ID_ADMIN INT NOT NULL,
	FIRSTNAME VARCHAR(30) NOT NULL,
	LASTNAME VARCHAR(30) NOT NULL,
	PHONENUM BIGINT NOT NULL,
	ADMIN_PASSWORD NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_ADMINS PRIMARY KEY (ID_ADMIN))
END
					  
GO
					  
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = 'DOCTORS')
BEGIN
	ALTER TABLE DOCTORS ALTER COLUMN DOC_PASSWORD NVARCHAR(MAX) NOT NULL
END
					  
GO
