USE LV_310_DENTISTRY

GO

IF object_id('spGetEvents') IS NULL
EXEC ('create procedure dbo.spGetEvents as select 1')
GO

ALTER PROCEDURE spGetEvents
 @DOCTOR_ID INT
AS
    DECLARE
	 @Events table (EVENT_ID INT,DOCTOR_ID INT ,USER_ID INT ,TITLE VARCHAR(30) ,DESCRIPTIO VARCHAR(100) ,START_EVENT DATETIME ,END_EVENT DATETIME ,IS_BOOKED BIT )

    insert @Events  select EVENT_ID,DOCTOR_ID,USER_ID,TITLE,DESCRIPTIO,START_EVENT,END_EVENT,IS_BOOKED from CALENDAR_EVENT 

    select * from @Events WHERE DOCTOR_ID=@DOCTOR_ID
RETURN;

GO
ALTER PROCEDURE spAddDoctor
@FIRSTNAME VARCHAR(30), @LASTNAME VARCHAR(30), @PHONENUM BIGINT,@CABNUM TINYINT,@SPECIALITY VARCHAR(30), @DOC_PASSWORD NVARCHAR(MAX)
AS
BEGIN
INSERT INTO DOCTORS(FIRSTNAME, LASTNAME, PHONENUM,CABNUM,SPECIALITY, DOC_PASSWORD)
VALUES (@FIRSTNAME, @LASTNAME, @PHONENUM,@CABNUM,@SPECIALITY, @DOC_PASSWORD)
END;

GO
ALTER PROCEDURE spCheckDoctor
@PHONENUM BIGINT, @COUNT INT OUTPUT
AS
BEGIN
SELECT @COUNT = count(*) 
FROM DOCTORS
WHERE PHONENUM = @PHONENUM
END;