USE LV_310_DENTISTRY;

IF object_id('spCheckLogin') IS NULL
    EXEC ('create procedure dbo.spCheckLogin as select 1')
GO
ALTER PROCEDURE spCheckLogin
@PHONENUM BIGINT, @USER_PASSWORD NVARCHAR(MAX) OUTPUT,@ID_USER INT OUTPUT,@FIRSTNAME VARCHAR(30) OUTPUT, @LASTNAME VARCHAR(30) OUTPUT, @ROLE VARCHAR(30) OUTPUT
AS
BEGIN

IF (SELECT COUNT(PHONENUM) FROM ADMINS WHERE PHONENUM = @PHONENUM) = 1
BEGIN
SELECT @USER_PASSWORD = ADMIN_PASSWORD , @ID_USER = ID_ADMIN , @FIRSTNAME=FIRSTNAME , @LASTNAME=LASTNAME , @ROLE = 'admin'
FROM ADMINS
WHERE PHONENUM = @PHONENUM
END

IF (SELECT COUNT(PHONENUM) FROM DOCTORS WHERE PHONENUM = @PHONENUM) = 1
BEGIN
SELECT @USER_PASSWORD = DOC_PASSWORD , @ID_USER = ID_DOCTOR , @FIRSTNAME=FIRSTNAME , @LASTNAME=LASTNAME , @ROLE = 'doctor'
FROM DOCTORS 
WHERE PHONENUM = @PHONENUM
END

IF (SELECT COUNT(PHONENUM) FROM USERS WHERE PHONENUM = @PHONENUM) = 1
BEGIN
SELECT @USER_PASSWORD = USER_PASSWORD , @ID_USER = ID_USER , @FIRSTNAME=FIRSTNAME , @LASTNAME=LASTNAME , @ROLE = 'user'
FROM USERS 
WHERE PHONENUM = @PHONENUM
END

END;