IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = 'TEETH')
BEGIN
	CREATE TABLE TEETH(
	ID INT NOT NULL IDENTITY(1,1),
	USER_ID INT NOT NULL,
	TOOTH_NUMBER INT NOT NULL,
	DESCRIPTIO NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_TOOTH PRIMARY KEY (ID),
	CONSTRAINT FK_USERS FOREIGN KEY(USER_ID) REFERENCES USERS(ID_USER))
END;

GO

IF object_id('spCheckTooth') IS NULL
    EXEC ('create procedure dbo.spCheckTooth as select 1')
GO
ALTER PROCEDURE dbo.spCheckTooth
@TOOTH_NUMBER INT,@USER_ID INT, @COUNT INT OUTPUT
AS
BEGIN
SELECT @COUNT = count(*) 
FROM TEETH
WHERE TOOTH_NUMBER = @TOOTH_NUMBER AND USER_ID = @USER_ID
END;

GO

IF object_id('spGetToothByNumber') IS NULL
    EXEC ('create procedure dbo.spGetToothByNumber as select 1')
GO
ALTER PROCEDURE dbo.spGetToothByNumber
@TOOTH_NUMBER INT, @USER_ID INT
AS
BEGIN
SELECT * FROM TEETH
WHERE TOOTH_NUMBER = @TOOTH_NUMBER AND USER_ID = @USER_ID
END;

GO

IF object_id('spGetTeethByUserId') IS NULL
    EXEC ('create procedure dbo.spGetTeethByUserId as select 1')
GO
ALTER PROCEDURE dbo.spGetTeethByUserId
@USER_ID INT
AS
BEGIN
SELECT * FROM TEETH
WHERE USER_ID = @USER_ID
END;


GO

IF object_id('spAddTooth') IS NULL
    EXEC ('create procedure dbo.spAddTooth  as select 1')
GO
ALTER PROCEDURE spAddTooth
@USER_ID INT, @TOOTH_NUMBER INT, @DESCRIPTIO NVARCHAR(MAX)
AS
BEGIN
INSERT INTO TEETH (USER_ID, TOOTH_NUMBER, DESCRIPTIO) VALUES (@USER_ID, @TOOTH_NUMBER,@DESCRIPTIO)
END;

GO

IF object_id('spEditTooth') IS NULL
    EXEC ('create procedure dbo.spEditTooth  as select 1')
GO
ALTER PROCEDURE spEditTooth
@USER_ID INT, @TOOTH_NUMBER INT, @DESCRIPTIO NVARCHAR(MAX)
AS
BEGIN
UPDATE TEETH
SET DESCRIPTIO = @DESCRIPTIO
WHERE TOOTH_NUMBER = @TOOTH_NUMBER AND USER_ID = @USER_ID
END;
