IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
           WHERE TABLE_NAME = 'XRAY')
BEGIN
	CREATE TABLE XRAY(
	ID INT NOT NULL IDENTITY(1,1),
	USER_ID INT NOT NULL,
	link NVARCHAR(256) NOT NULL,
	xray_DATE DATE  NOT NULL,
	CONSTRAINT PK_XRAY PRIMARY KEY (ID),
	CONSTRAINT FK_USERS_XRAY FOREIGN KEY(USER_ID) REFERENCES USERS(ID_USER))
END;